# Python 기초 문법

### 주요 내용

1. int, str, 리스트 등 주요 객체 형식
2. numpy를 활용한 행렬 연산
3. pandas를 활용한 데이터 활용

<br>

### 목표 
1. int, str 등 객체 형식에 따라 적절한 메서드를 활용한다.
2. 여러 개의 값을 리스트 형식 등으로 저장하고 활용한다.
3. numpy와 pandas을 적절히 활용한다.


<br>
<hr>
<br>


<br>

## 1. 형식의 이해



<br>



### 1.1. 숫자와 문자, 출력과 저장(할당)

숫자는 그냥 입력하면 되고, 문자는 쌍따옴표(")나 작은 따옴표(')를 붙임  
`print( )` 함수를 써서 출력하거나 `=`을 써서 값을 객체로 저장할 수도 있음

In [1]:
# 숫자와 연산
    ## 마지막 결과만 출력
    ## 중간 공백은 상관 없음
1 + 2 * 3 / 4

1 + 2  * 3/  4**5

1.005859375

In [5]:
# 문자
## 큰따옴표, 작은따옴표 차이 없음
'삼성전자'

'삼성전자'

In [6]:
"삼성전자"

'삼성전자'

In [10]:
# 할당(assign), 저장
## '+' : 숫자 덧셈 연산, 문자열 결합
a = '가나다'
b = '라마바'
a + b

'가나다라마바'

In [11]:
# type()으로 타입 확인하기
type(1)

int

In [12]:
type('가')

str

In [13]:
# int : 정수형(3)
# float : 실수형(3.14)
# str : 문자열('아침')

#### [실습] x에 10.1을 저장하고, y에 101을 저장한 다음 더하기

In [2]:
x = 10.1
y = 101
x + y

111.1


<br>

### 1.2. 여러 값을 묶은 리스트(list)

`1`, `'삼성'`처럼 하나의 값이 아니라 여러개의 값을 묶으면 수열, 문자열이 생성  
Python에서는 **리스트(list)** 형식 등으로 수열, 문자열을 다룸  

<br>

#### 1.2.1. 대괄호([ ])를 활용한 리스트 생성

In [3]:
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [4]:
# 타입 확인 : list
type(salary)

list

In [5]:
# 문자열 리스트
jobs = ['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']
jobs

['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']

In [6]:
# 리스트의 길이 확인
len(jobs)

7

In [8]:
2*3 # 곱셈

6

In [10]:
# ** : 지수승
2**3

8

In [12]:
# 나머지 구하기
7%5

2

#### [실습] 1~10까지 숫자 중에서 마음대로 3개 숫자 선택해서 리스트로 만들어 저장하기



#### [실습] 점심/저녁 메뉴 3개를 리스트로 묶어 menu로 저장하기 



In [14]:
list_num = [3, 5, 8]
list_num

[3, 5, 8]

In [15]:
menu = ['자장면', '볶음밥', '우동']
menu

['자장면', '볶음밥', '우동']

<br>

#### 1.2.2. 리스트의 주요 메서드

append( )는 리스트에 값을 추가

In [22]:
# 더 이어 붙이기 
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [23]:
salary.append(10000)
salary

[5000, 6000, 7000, 6000, 9000, 10000]

#### [실습] 관심있는 메뉴 3개를 묶은 menu에 append( )로 메뉴 하나 더 추가하기



In [16]:
menu.append('볶음밥')
menu

['자장면', '볶음밥', '우동', '볶음밥']

<br>

#### 1.2.3. index의 활용   

리스트를 만들 때 사용한 대괄호와 별개로, 만들어진 리스트에 대괄호 인덱스를 활용해서 부분을 선택



In [26]:
salary

[5000, 6000, 7000, 6000, 9000, 10000]

In [25]:
# 대괄호 index를 활용한 부분 선택
## index는 0부터 시작 : 첫번째 값이 0
## 콜론(:)을 활용해 연속적인 인덱스 지정 가능(슬라이싱), 끝 인덱스 미포함
salary[0] 

5000

In [29]:
salary[0:2]
# salary[:2] # 처음부터 2미만까지
# salary[2:] # 2부터 끝까지

[5000, 6000]

In [30]:
# 인덱스를 활용한 업데이트
salary[0] = 50000
salary

[50000, 6000, 7000, 6000, 9000, 10000]

#### [실습] menu에서 첫번째 메뉴만 선택


#### [실습] menu에서 세번째 메뉴를 '우동'으로 변경



In [17]:
menu[0]

'자장면'

In [18]:
menu[2] = '우동'

In [19]:
menu

['자장면', '볶음밥', '우동', '볶음밥']


<br>

#### 1.2.4. range( )를 활용한 수열 만들기

연속적인 수열을 만들 때는 `range( )`를 활용


In [20]:
# 0부터 시작하는 range
range(10)

range(0, 10)

In [21]:
# range( )와 list( )를 활용한 수열 생성
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
list(range(1, 20))
## 1부터 20 바로 앞 19까지

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [23]:
list(range(1, 20, 3))
## 1부터 19까지 3간격

[1, 4, 7, 10, 13, 16, 19]

<br>

#### [실습] range( )와 list( )로 2013부터 2022까지 10개 연도 만들기




In [24]:
list(range(2013, 2023))

[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

### 1.3. for 반복문 예제

In [25]:
# 간단한 for 예제
count = 0

for i in [11, 12, 13]:
#     count += 1 ## 반복할 때마다 1씩 증가 (count = count + 1)
#     print(str(count) + '번째 값은 '+ str(i))
    print(i)

11
12
13


<br>
<br>
<br>


## 2. numpy의 활용 

**numpy**는 *ndarray*라는 형식을 활용해서 다양한 행렬 연산과 처리를 지원


### 2.1. ndarray 생성 

In [47]:
import numpy as np

In [26]:
# 리스트 형식을 ndarray 형식으로 변환하기
x = [1, 2, 4, 8]
y = np.array(x)
y

array([1, 2, 4, 8])

In [27]:
# 형식 확인
type(y)

numpy.ndarray

In [28]:
# 수열 생성
## 0부터 10까지 101개 실수
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [29]:
# 랜덤 숫자 뽑기(1부터 46까지 6개)
np.random.randint(1, 46, 6)

array([39,  7,  7, 30, 35, 44])

In [30]:
# 중첩(nested) 리스트를 활용한 다차원 행렬 만들기
y2 = np.array([ [1,2,3,4], [9,8,7,6] ])
y3 = np.array([ [0, 1], [1, 0] ])

y2, y3              

(array([[1, 2, 3, 4],
        [9, 8, 7, 6]]),
 array([[0, 1],
        [1, 0]]))

In [31]:
# 행렬 크기 확인
y2.shape
## 2x4, 2행 4열, 2개 관측치 4개 변수

(2, 4)

<br>

### 2.2. ndarray와 연산 

numpy에는 ndarray에 적용할 수 있는 다양한 연산자와 함수가 준비되어 있음

In [32]:
y2  # 2x4 행렬

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [33]:
y3  # 2x2 행렬

array([[0, 1],
       [1, 0]])

In [34]:
# 산술 연산
y2 * 2 + 1

array([[ 3,  5,  7,  9],
       [19, 17, 15, 13]])

In [35]:
# 행렬 곱
y3@y2   # 2x2행렬 곱 2x4행렬 => 2x4 행렬

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [36]:
# 전체 합계
np.sum(y2)

40

In [37]:
# 열 합계
np.sum(y2, axis=0)

array([10, 10, 10, 10])

In [38]:
# 행 합계
np.sum(y2, axis=1)

array([10, 30])

In [39]:
# 행 평균
np.mean(y2, axis=1)

array([2.5, 7.5])

<br>

### 2.3. 부분 선택
대괄호 인덱스를 활용하여 ndarray에서 일부를 선택할 수 있습니다. 

In [40]:
y

array([1, 2, 4, 8])

In [41]:
# 특정 인덱스 선택
y[1]

2

In [42]:
# 슬라이스 활용
y[1:]

array([2, 4, 8])

In [43]:
y[:2]

array([1, 2])

In [79]:
y[:-1]

array([1, 2, 4])

In [44]:
# 다차원 행렬의 부분 선택
# 콤마 앞은 행, 뒤는 열
y2[:, :]

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [45]:
y2[0, 1:3]

array([2, 3])

<br>

#### [실습] 행렬 생성 및 연산
1. 아래의 행렬을 만들고 *mat*으로 저장하기

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \\ 2 & 1 & 1 \end{bmatrix}$$

2. `np.max()`을 활용해서 *mat*에서 전체 최댓값 계산하기

3. `np.mean()`을 활용해서 *mat*에서 행 평균 계산하기

4. 첫번째부터 세번째 행의 두번째 열 선택


In [47]:
import numpy as np

# 아래의 행렬을 만들고 mat으로 저장하기
mat = np.array([  [1,2,1], 
                  [3,0,1],
                  [0,2,4], 
                  [2,1,1] ])
mat

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4],
       [2, 1, 1]])

In [48]:
np.max(mat)

4

In [49]:
np.mean(mat, axis=1)

array([1.33333333, 1.33333333, 2.        , 1.33333333])

In [50]:
mat[0:3, 1]

array([2, 0, 2])

### 2.4. 길이와 거리 계산

ndarray를 활용해서 길이나 관측치 간 거리를 계산 가능

In [51]:
a = np.array([1, 3])
b = np.array([4, 3])

In [52]:
# 길이(norm) 계산
# linalg : linear algebra
np.linalg.norm(a), np.linalg.norm(b)

(3.1622776601683795, 5.0)

In [53]:
# 거리 계산
print(np.linalg.norm(a-b))

3.0


<br>
<br>
<br>

## 3. pandas의 활용

**pandas** 라이브러리의 *read_csv()* 등의 함수를 활용해서 csv 등 데이터 불러오기 가능 

<br>

### 3.1. CSV 파일 불러오기



In [54]:
# pandas 라이브러리 불러오기
import pandas as pd

In [58]:
# pandas의 read_csv( ) 활용
df_ins= pd.read_csv("./data/insurance.csv")
df_ins= pd.read_csv("data/insurance.csv")

print(df_ins.shape)
df_ins.head()
    ## 경로가 중요! 
    ## ./ : ipynb 노트북 파일 폴더
    ## ./ 생략 가능
    ## Tab으로 자동 완성 기능 활용 가능 

(1338, 7)


age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [61]:
df_ins['age']   # series(1차원)

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [62]:
# 1차원 : series
# 2차원 : dataframe(행, 열)

In [63]:
# 타입 확인
type(df_ins)
    ## "DataFrame"

pandas.core.frame.DataFrame

In [66]:
# 메서드(함수)의 확인(마침표 뒤에서 Tab 누르기)
df_ins.

In [67]:
# columns(변수 이름) 확인
df_ins.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

<br>

#### [함께 실습] data 폴더의 PulseRates.csv를 불러와서 df_pr로 저장하기

이후 데이터 탐색하기

In [68]:
import pandas as pd

df_pr = pd.read_csv("./data/PulseRates.csv")
# df_pr = pd.read_excel("./data/PulseRates.xlsx")

print(df_pr.shape)
df_pr.head(5)

(110, 11)


Height  Weight  Age  Gender  Smokes  Alcohol  Exercise  Ran  Pulse1  \
0     173    57.0   18       2       2        1         2    2    86.0   
1     179    58.0   19       2       2        1         2    1    82.0   
2     167    62.0   18       2       2        1         1    1    96.0   
3     195    84.0   18       1       2        1         1    2    71.0   
4     173    64.0   18       2       2        1         3    2    90.0   

   Pulse2  Year  
0    88.0    93  
1   150.0    93  
2   176.0    93  
3    73.0    93  
4    88.0    93

<br>

### 3.2. 변수 선택 

대괄호 인덱스에 변수 이름을 입력하고 변수를 선택 가능  
리스트로 변수 이름을 묶고 여러 변수를 한번에 선택 가능

In [69]:
# 한 변수 선택 
    # Series 형식으로 출력됨
df_ins['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [70]:
# 한 변수 선택 
    # DataFrame 형식으로 출력됨
df_ins[['age']]

age
0      19
1      18
2      28
3      33
4      32
...   ...
1333   50
1334   18
1335   18
1336   21
1337   61

[1338 rows x 1 columns]

In [71]:
# 리스트를 활용한 복수 변수 선택
df_ins[['age','smoker','charges']]

age smoker      charges
0      19    yes  16884.92400
1      18     no   1725.55230
2      28     no   4449.46200
3      33     no  21984.47061
4      32     no   3866.85520
...   ...    ...          ...
1333   50     no  10600.54830
1334   18     no   2205.98080
1335   18     no   1629.83350
1336   21     no   2007.94500
1337   61    yes  29141.36030

[1338 rows x 3 columns]

<br>

### 3.3. 관측치 부분 선택

특정 변수를 선택한 다음 조건을 설정하고 실행하면 True/False로 구성된 bool Series가 계산됨
bool Series를 데이터 대괄호 인덱스에 넣어 조건과 일치하는 관측치를 선택 가능

In [72]:
# 변수 선택
df_ins['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [73]:
# 조건 설정
df_ins['age'] < 30

0        True
1        True
2        True
3       False
4       False
        ...  
1333    False
1334     True
1335     True
1336     True
1337    False
Name: age, Length: 1338, dtype: bool

In [74]:
# 조건과 일치하는 관측치 선택
df_ins[df_ins['age'] < 30]

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
10     25    male  26.220         0     no  northeast   2721.32080
12     23    male  34.400         0     no  southwest   1826.84300
...   ...     ...     ...       ...    ...        ...          ...
1328   23  female  24.225         2     no  northeast  22395.74424
1331   23  female  33.400         0     no  southwest  10795.93733
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500

[417 rows x 7 columns]

In [77]:
# 조건을 활용한 특정 그룹 선택 : df[df_조건]
df_ins_male = df_ins[ df_ins['sex'] == 'male' ] 
df_ins_male

age   sex     bmi  children smoker     region      charges
1      18  male  33.770         1     no  southeast   1725.55230
2      28  male  33.000         3     no  southeast   4449.46200
3      33  male  22.705         0     no  northwest  21984.47061
4      32  male  28.880         0     no  northwest   3866.85520
8      37  male  29.830         2     no  northeast   6406.41070
...   ...   ...     ...       ...    ...        ...          ...
1324   31  male  25.935         1     no  northwest   4239.89265
1325   61  male  33.535         0     no  northeast  13143.33665
1327   51  male  30.030         1     no  southeast   9377.90470
1329   52  male  38.600         2     no  southwest  10325.20600
1333   50  male  30.970         3     no  northwest  10600.54830

[676 rows x 7 columns]

<br>

#### [실습] 데이터 불러오기 및 부분 선택

1. `data`폴더에서 `StudentsPerformance.csv`를 불러와서 **df_sp**로 저장하기
2. **df_sp**에서 `math score`, `reading score`, `writing score` 세 변수 선택하기
3. **df_sp**에서 `math score`가 90이상인 관측치 선택하기
4. **df_sp**에서 `gender`가 *'female'*인 관측치 선택하기

In [78]:
df_sp = pd.read_csv('data/StudentsPerformance.csv')

print(df_sp.shape)
df_sp.head(1)

(1000, 8)


gender race/ethnicity parental level of education     lunch  \
0  female        group B           bachelor's degree  standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74

In [79]:
# 2번
df_sp[['math score', 'reading score', 'writing score']].head(1)

math score  reading score  writing score
0          72             72             74

In [80]:
# 3번
df_sp[df_sp['math score'] >= 90].head(1)

gender race/ethnicity parental level of education     lunch  \
2  female        group B             master's degree  standard   

  test preparation course  math score  reading score  writing score  
2                    none          90             95             93

In [81]:
# 4번
df_sp[df_sp['gender'] == 'female'].head(1)

gender race/ethnicity parental level of education     lunch  \
0  female        group B           bachelor's degree  standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74

### [참고] list, np.array, pd.Series의 호환

In [82]:
# pandas의 Series
df_ins['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [101]:
# Series의 list 변환 - 2가지 방법
list(df_ins['age'])
print(df_ins['age'].to_list())

[19, 18, 28, 33, 32, 31, 46, 37, 37, 60, 25, 62, 23, 56, 27, 19, 52, 23, 56, 30, 60, 30, 18, 34, 37, 59, 63, 55, 23, 31, 22, 18, 19, 63, 28, 19, 62, 26, 35, 60, 24, 31, 41, 37, 38, 55, 18, 28, 60, 36, 18, 21, 48, 36, 40, 58, 58, 18, 53, 34, 43, 25, 64, 28, 20, 19, 61, 40, 40, 28, 27, 31, 53, 58, 44, 57, 29, 21, 22, 41, 31, 45, 22, 48, 37, 45, 57, 56, 46, 55, 21, 53, 59, 35, 64, 28, 54, 55, 56, 38, 41, 30, 18, 61, 34, 20, 19, 26, 29, 63, 54, 55, 37, 21, 52, 60, 58, 29, 49, 37, 44, 18, 20, 44, 47, 26, 19, 52, 32, 38, 59, 61, 53, 19, 20, 22, 19, 22, 54, 22, 34, 26, 34, 29, 30, 29, 46, 51, 53, 19, 35, 48, 32, 42, 40, 44, 48, 18, 30, 50, 42, 18, 54, 32, 37, 47, 20, 32, 19, 27, 63, 49, 18, 35, 24, 63, 38, 54, 46, 41, 58, 18, 22, 44, 44, 36, 26, 30, 41, 29, 61, 36, 25, 56, 18, 19, 39, 45, 51, 64, 19, 48, 60, 27, 46, 28, 59, 35, 63, 40, 20, 40, 24, 34, 45, 41, 53, 27, 26, 24, 34, 53, 32, 19, 42, 55, 28, 58, 41, 47, 42, 59, 19, 59, 39, 40, 18, 31, 19, 44, 23, 33, 55, 40, 63, 54, 60, 24, 19, 29,

In [99]:
# Series의 np.array 변환 - 2가지 방법
np.array(df_ins['age'])
print(df_ins['age'].to_numpy())

[19 18 28 ... 18 21 61]


In [85]:
# list의 Series 변환
pd.Series(['A','B','B','A'])

0    A
1    B
2    B
3    A
dtype: object

In [86]:
# Series의 .mean() 활용 평균 계산
df_ins['age'].mean()

39.20702541106129

In [87]:
# numpy.mean() 활용 평균 계산
np.mean(df_ins['age'])

39.20702541106129

In [89]:
df_ins.describe()  # describe함수를 이용하면 더 쉽게 통계값들을 확인할 수 있다.

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

# 집계

In [90]:
df_ins['age'].count()
df_ins['age'].sum()
df_ins['age'].mean()

df_ins.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [91]:
df_ins.groupby('sex')['age'].mean()

sex
female    39.503021
male      38.917160
Name: age, dtype: float64

In [92]:
df_ins['sex'].unique()

array(['female', 'male'], dtype=object)

In [93]:
df_ins['sex'].nunique()

2

In [94]:
df_ins['sex'].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [95]:
# 흡연자, 나이 분포 교차표
pd.crosstab(df_ins['smoker'], df_ins['sex'])

sex     female  male
smoker              
no         547   517
yes        115   159

In [96]:
# 행기준 교차표
pd.crosstab(df_ins['smoker'], df_ins['sex'], normalize='index')

sex       female      male
smoker                    
no      0.514098  0.485902
yes     0.419708  0.580292

In [97]:
# 열기준 교차표
pd.crosstab(df_ins['smoker'], df_ins['sex'], normalize='columns')

sex       female      male
smoker                    
no      0.826284  0.764793
yes     0.173716  0.235207

In [98]:
## 피벗 테이블
pd.pivot_table(df_ins, index='smoker', columns='sex', values='age', aggfunc='mean')
df_ins.pivot_table(index='smoker', columns='sex', values='age', aggfunc='mean')

sex        female       male
smoker                      
no      39.691042  39.061896
yes     38.608696  38.446541

#### End of script