# Python 기초 문법

### 주요 내용

1. int, str, 리스트 등 주요 객체 형식
2. numpy를 활용한 행렬 연산
3. pandas를 활용한 데이터 활용

<br>

### 목표 
1. int, str 등 객체 형식에 따라 적절한 메서드를 활용한다.
2. 여러 개의 값을 리스트 형식 등으로 저장하고 활용한다.
3. numpy와 pandas을 적절히 활용한다.


<br>
<hr>
<br>


<br>

## 1. 형식의 이해



<br>



### 1.1. 숫자와 문자, 출력과 저장(할당)

숫자는 그냥 입력하면 되고, 문자는 쌍따옴표(")나 작은 따옴표(')를 붙임  
`print( )` 함수를 써서 출력하거나 `=`을 써서 값을 객체로 저장할 수도 있음

In [4]:
# 숫자와 연산
    ## 마지막 결과만 출력
    ## 중간 공백은 상관 없음
1 + 2 * 3 / 4

1 + 2  * 3/  4**5

1.005859375

In [5]:
# 문자
## 큰따옴표, 작은따옴표 차이 없음
'삼성전자'

'삼성전자'

In [6]:
"삼성전자"

'삼성전자'

In [10]:
# 할당(assign), 저장
## '+' : 숫자 덧셈 연산, 문자열 결합
a = '가나다'
b = '라마바'
a + b

'가나다라마바'

In [11]:
# type()으로 타입 확인하기
type(1)

int

In [12]:
type('가')

str

In [13]:
# int : 정수형(3)
# float : 실수형(3.14)
# str : 문자열('아침')

#### [실습] x에 10.1을 저장하고, y에 101을 저장한 다음 더하기

In [15]:
x = 10.1
y = 101
x + y

111.1


<br>

### 1.2. 여러 값을 묶은 리스트(list)

`1`, `'삼성'`처럼 하나의 값이 아니라 여러개의 값을 묶으면 수열, 문자열이 생성  
Python에서는 **리스트(list)** 형식 등으로 수열, 문자열을 다룸  

<br>

#### 1.2.1. 대괄호([ ])를 활용한 리스트 생성

In [17]:
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [18]:
# 타입 확인 : list
type(salary)

list

In [19]:
# 문자열 리스트
jobs = ['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']
jobs

['회로설계', '반도체공정설계', '신호 및 시스템 설계', 'S/W개발', '영업마케팅', '경영지원', '생산관리']

#### [실습] 1~10까지 숫자 중에서 마음대로 3개 숫자 선택해서 리스트로 만들어 저장하기



#### [실습] 점심/저녁 메뉴 3개를 리스트로 묶어 menu로 저장하기 



In [20]:
list_num = [1 ,3, 5]
list_num

[1, 3, 5]

In [32]:
menu = ['짜장면', '돈까스', '김치찌개']
menu

['짜장면', '돈까스', '김치찌개']

<br>

#### 1.2.2. 리스트의 주요 메서드

append( )는 리스트에 값을 추가

In [22]:
# 더 이어 붙이기 
salary = [5000, 6000, 7000, 6000, 9000]
salary

[5000, 6000, 7000, 6000, 9000]

In [23]:
salary.append(10000)
salary

[5000, 6000, 7000, 6000, 9000, 10000]

#### [실습] 관심있는 메뉴 3개를 묶은 menu에 append( )로 메뉴 하나 더 추가하기



In [33]:
menu.append('볶음밥')
menu

['짜장면', '돈까스', '김치찌개', '볶음밥']

<br>

#### 1.2.3. index의 활용   

리스트를 만들 때 사용한 대괄호와 별개로, 만들어진 리스트에 대괄호 인덱스를 활용해서 부분을 선택



In [26]:
salary

[5000, 6000, 7000, 6000, 9000, 10000]

In [25]:
# 대괄호 index를 활용한 부분 선택
## index는 0부터 시작 : 첫번째 값이 0
## 콜론(:)을 활용해 연속적인 인덱스 지정 가능(슬라이싱), 끝 인덱스 미포함
salary[0] 

5000

In [29]:
salary[0:2]
# salary[:2] # 처음부터 2미만까지
# salary[2:] # 2부터 끝까지

[5000, 6000]

In [30]:
# 인덱스를 활용한 업데이트
salary[0] = 50000
salary

[50000, 6000, 7000, 6000, 9000, 10000]

#### [실습] menu에서 첫번째 메뉴만 선택


#### [실습] menu에서 세번째 메뉴를 '우동'으로 변경



In [34]:
menu[0]

'짜장면'

In [35]:
menu[2] = '우동'

'짜장면'

In [36]:
menu

['짜장면', '돈까스', '우동', '볶음밥']


<br>

#### 1.2.4. range( )를 활용한 수열 만들기

연속적인 수열을 만들 때는 `range( )`를 활용


In [37]:
# 0부터 시작하는 range
range(10)

range(0, 10)

In [38]:
# range( )와 list( )를 활용한 수열 생성
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
list(range(1, 20))
## 1부터 20 바로 앞 19까지

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [40]:
list(range(1, 20, 3))
## 1부터 19까지 3간격

[1, 4, 7, 10, 13, 16, 19]

<br>

#### [실습] range( )와 list( )로 2013부터 2022까지 10개 연도 만들기




In [41]:
list(range(2013, 2023))

[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

### 1.3. for 반복문 예제

In [42]:
# 간단한 for 예제
count = 0

for i in [11, 12, 13]:
    count += 1 ## 반복할 때마다 1씩 증가 (count = count + 1)
    print(str(count) + '번째 값은 '+ str(i))
# str() : 문자열로 만들어주는 함수

1번째 값은 11
2번째 값은 12
3번째 값은 13


In [46]:
# 단순화
count = 0

for i in [11, 12, 13]:
    #count += 1 ## 반복할 때마다 1씩 증가 (count = count + 1)
    print(i)
# str() : 문자열로 만들어주는 함수

11
12
13


<br>
<br>
<br>


## 2. numpy의 활용 

**numpy**는 *ndarray*라는 형식을 활용해서 다양한 행렬 연산과 처리를 지원


### 2.1. ndarray 생성 

In [47]:
import numpy as np

In [48]:
# 리스트 형식을 ndarray 형식으로 변환하기
x = [1, 2, 4, 8]
y = np.array(x)
y

array([1, 2, 4, 8])

In [49]:
# 형식 확인
type(y)

numpy.ndarray

In [51]:
# 수열 생성
## 0부터 10까지 101개 실수
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [61]:
# 랜덤 숫자 뽑기(1부터 46까지 6개)
np.random.randint(1, 46, 6)

array([16,  7, 15, 17, 35, 25])

In [62]:
# 중첩(nested) 리스트를 활용한 다차원 행렬 만들기
y2 = np.array([ [1,2,3,4], [9,8,7,6] ])
y3 = np.array([ [0, 1], [1, 0] ])

y2, y3              

(array([[1, 2, 3, 4],
        [9, 8, 7, 6]]),
 array([[0, 1],
        [1, 0]]))

In [63]:
# 행렬 크기 확인
y2.shape
## 2x4, 2행 4열, 2개 관측치 4개 변수

(2, 4)

<br>

### 2.2. ndarray와 연산 

numpy에는 ndarray에 적용할 수 있는 다양한 연산자와 함수가 준비되어 있음

In [66]:
y2  # 2x4 행렬

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [69]:
y3  # 2x2 행렬

array([[0, 1],
       [1, 0]])

In [67]:
# 산술 연산
y2 * 2 + 1

array([[ 3,  5,  7,  9],
       [19, 17, 15, 13]])

In [68]:
# 행렬 곱
y3@y2   # 2x2행렬 곱 2x4행렬 => 2x4 행렬

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [70]:
# 전체 합계
np.sum(y2)

40

In [71]:
# 열 합계
np.sum(y2, axis=0)

array([10, 10, 10, 10])

In [74]:
# 행 합계
np.sum(y2, axis=1)

array([10, 30])

In [72]:
# 행 평균
np.mean(y2, axis=1)

array([2.5, 7.5])

<br>

### 2.3. 부분 선택
대괄호 인덱스를 활용하여 ndarray에서 일부를 선택할 수 있습니다. 

In [75]:
y

array([1, 2, 4, 8])

In [76]:
# 특정 인덱스 선택
y[1]

2

In [77]:
# 슬라이스 활용
y[1:]

array([2, 4, 8])

In [78]:
y[:2]

array([1, 2])

In [79]:
y[:-1]

array([1, 2, 4])

In [80]:
# 다차원 행렬의 부분 선택
# 콤마 앞은 행, 뒤는 열
y2[:, :]

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [83]:
y2[0, 1:3]

array([2, 3])

<br>

#### [실습] 행렬 생성 및 연산
1. 아래의 행렬을 만들고 *mat*으로 저장하기

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \\ 2 & 1 & 1 \end{bmatrix}$$

2. `np.max()`을 활용해서 *mat*에서 전체 최댓값 계산하기

3. `np.mean()`을 활용해서 *mat*에서 행 평균 계산하기

4. 첫번째부터 세번째 행의 두번째 열 선택


In [86]:
np.max(mat)

4

In [87]:
np.mean(mat, axis=1)

array([1.33333333, 1.33333333, 2.        ])

In [93]:
mat[2, 0]

TypeError: list indices must be integers or slices, not tuple

### 2.4. 길이와 거리 계산

ndarray를 활용해서 길이나 관측치 간 거리를 계산 가능

In [ ]:
a = np.array([1,3])
b = np.array([4,3])

In [ ]:
# 길이(norm) 계산
# linalg : linear algebra
np.linalg.norm(a), np.linalg.norm(b)

In [ ]:
# 거리 계산
print(np.linalg.norm(a-b))

<br>
<br>
<br>

## 3. pandas의 활용

**pandas** 라이브러리의 *read_csv()* 등의 함수를 활용해서 csv 등 데이터 불러오기 가능 

<br>

### 3.1. CSV 파일 불러오기



In [ ]:
# pandas 라이브러리 불러오기
import pandas as pd

In [ ]:
# pandas의 read_csv( ) 활용
df_ins= pd.read_csv("./data/insurance.csv")
df_ins= pd.read_csv("data/insurance.csv")
df_ins    
    ## 경로가 중요! 
    ## ./ : ipynb 노트북 파일 폴더
    ## ./ 생략 가능
    ## Tab으로 자동 완성 기능 활용 가능 

In [ ]:
# 타입 확인
type(df_ins)
    ## "DataFrame"

In [ ]:
# 메서드의 확인(마침표 뒤에서 Tab 누르기)
df_ins.

In [ ]:
# columns(변수 이름) 확인
df_ins.columns

<br>

#### [함께 실습] data 폴더의 PulseRates.csv를 불러와서 df_pr로 저장하기

이후 데이터 탐색하기

<br>

### 3.2. 변수 선택 

대괄호 인덱스에 변수 이름을 입력하고 변수를 선택 가능  
리스트로 변수 이름을 묶고 여러 변수를 한번에 선택 가능

In [ ]:
# 한 변수 선택 
    # Series 형식으로 출력됨
df_ins['age']

In [ ]:
# 한 변수 선택 
    # DataFrame 형식으로 출력됨
df_ins[['age']]

In [ ]:
# 리스트를 활용한 복수 변수 선택
df_ins[['age','smoker','charges']]

<br>

### 3.3. 관측치 부분 선택

특정 변수를 선택한 다음 조건을 설정하고 실행하면 True/False로 구성된 bool Series가 계산됨
bool Series를 데이터 대괄호 인덱스에 넣어 조건과 일치하는 관측치를 선택 가능

In [ ]:
# 변수 선택
df_ins['age']

In [ ]:
# 조건 설정
df_ins['age'] < 30

In [ ]:
# 조건과 일치하는 관측치 선택
df_ins[df_ins['age'] < 30]

In [ ]:
# 일치 여부를 활용한 특정 그룹 선택
df_ins_male = df_ins[ df_ins['sex'] == 'male' ] 
df_ins_male

<br>

#### [실습] 데이터 불러오기 및 부분 선택

1. `data`폴더에서 `StudentsPerformance.csv`를 불러와서 **df_sp**로 저장하기
2. **df_sp**에서 `math score`, `reading score`, `writing score` 세 변수 선택하기
3. **df_sp**에서 `math score`가 90이상인 관측치 선택하기
4. **df_sp**에서 `gender`가 *'female'*인 관측치 선택하기

### [참고] list, np.array, pd.Series의 호환

In [ ]:
# pandas의 Series
df_ins['age']

In [ ]:
# Series의 list 변환 - 2가지 방법
list(df_ins['age'])
df_ins['age'].to_list()

In [ ]:
# Series의 np.array 변환 - 2가지 방법
np.array(df_ins['age'])
df_ins['age'].to_numpy()

In [ ]:
# list의 Series 변환
pd.Series(['A','B','B','A'])

In [ ]:
# Series의 .mean() 활용 평균 계산
df_ins['age'].mean()

In [ ]:
# numpy.mean() 활용 평균 계산
np.mean(df_ins['age'])

#### End of script